foreground              #FFFFFF
background              #0F181B
selection_foreground    #0F181B
selection_background    #FFFFFF
cursor                  #8B272C
cursor_text_color       #FFFFFF

active_tab_foreground     #0F181B
active_tab_background     #5E2D35
inactive_tab_foreground   #5E2D35
inactive_tab_background   #0F181B

# black
color0      #294752
color8      #57818F

# red
color1      #FFCCCF
color9      #F0AAAE

# green
color2      #F9CCFF
color10     #E8AAF0

# yellow
color3      #FFCCD4
color11     #F0AAB6

# blue
color4      #9AD3E6
color12     #9AD3E6

# magenta
color5      #DD9AE6
color13     #DD9AE6

# cyan
color6      #E69AA6
color14     #E69AA6

# white
color7      #FFCCCF
color15     #F0AAAE
