
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hypr.land/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hypr.land/Configuring/Variables/#input
general {
    layout = scrolling
    gaps_in = 2
    gaps_out = 2
    border_size = 1
}

decoration {
    blur {
        special = false # for scratchpad
      }
  }
scrolling {
    fullscreen_on_one_column = true
    column_width = 0.50
    follow_focus = true
    #wrap_focus = true
    #wrap_swapcol = true
}
input {
    kb_layout = us
    kb_variant = dvorak

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}
layerrule = match:namespace waybar, blur 0 
exec-once = gnome-keyring-daemon --start --components=secrets 


# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    focus_on_activate = true
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}

# Force Qt applications to use Wayland and the correct IM module
#env = QT_QPA_PLATFORM,wayland
env = QT_IM_MODULE,wayland;fcitx
#env = XMODIFIERS,@im=fcitx
#env = SDL_IM_MODULE,fcitx
#env = GLFW_IM_MODULE,ibus
exec-once = fcixt5


