
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hypr.land/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hypr.land/Configuring/Variables/#input
exec-once = hyprpm reload

general {
    layout = scrolling
    gaps_in = 2
    gaps_out = 3
    border_size = 1
}

decoration {
    blur {
      enabled = true
      size = 2
      passes = 3
        special = false # for scratchpad
      }
  }

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.50
    follow_focus = true
    #wrap_focus = true
    #wrap_swapcol = true
}

input {
    kb_layout = us
    kb_variant = dvorak

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
    follow_mouse = 1
    sensitivity = 0.3   # Sets the speed. Range is -1.0 to 1.0 (0 means no change)
    accel_profile = flat # Options: 'flat' (disables acceleration) or 'adaptive'
    force_no_accel = 0   # Set to 1 if you want to bypass all acceleration profiles
}

layerrule = match:namespace waybar, blur 0 
exec-once = gnome-keyring-daemon --start --components=secrets 


# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    focus_on_activate = true
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}

plugin {
    scrolloverview {
        gesture_distance = 300 # how far is the "max" for the gesture
        scale = 0.5 # preferred overview scale
        workspace_gap = 50
        wallpaper = 0 # 0: global only, 1: per-workspace only, 2: both
        blur = true # blur only the main overview wallpaper

        shadow {
            enabled = false
            range = 100
            render_power = 3
            color = rgba(1a1a1aee)
        }
    }
}

# Force Qt applications to use Wayland and the correct IM module
#env = QT_QPA_PLATFORM,wayland
env = QT_IM_MODULE,wayland;fcitx
#env = XMODIFIERS,@im=fcitx
#env = SDL_IM_MODULE,fcitx
#env = GLFW_IM_MODULE,ibus
exec-once = fcixt5
exec-once = ~/center_mouse.sh
workspace = 4, layout:dwindle
